name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: ["*", "16", "14"]
    runs-on: ubuntu-latest
    name: ubuntu node@${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: ${{ matrix.node == '*' }}
      - name: install
        run: npm install
      - name: test
        run: npm test
    services:
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
