name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: hapijs/.github/.github/workflows/ci-plugin.yml@master
    with:
      min-node-version: 14
    services:
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
